version: '2'
services:
  squid:
    build: 
      context: .
      dockerfile: Dockerfile
#      dockerfile: Dockerfile-source
    volumes:
      - /home/roscom/:/home/roscom
      - /var/log/dockersquid/:/var/log/
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
